id: I37C6E52C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:43:32+00:00'
last_modified: '2022-06-07T14:03:15.935935+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29519
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་ཉི་མའི་འོད་ཟེར་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2246':
      image_group_id: I5287
      title: ''
      total_pages: 1198
      order: 1
      base_file: 2246.txt
    B3DE:
      image_group_id: I5288
      title: ''
      total_pages: 668
      order: 2
      base_file: B3DE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
