id: P001698
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:20.076299
source_metadata:
  id: bdr:W29519
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད་ཉི་མའི་འོད་ཟེར་ལེགས་བཤད་ལུང་གི་རྒྱ་མཚོ
  author: ''
  volumes:
    822be36594ee473f81bd00201a9ce2da:
      image_group_id: I5287
      title: ''
      volume_number: 1
      total_pages: 1198
      base_file: v001.txt
    9c9c0dc17170497392f1f74a138069e6:
      image_group_id: I5288
      title: ''
      volume_number: 2
      total_pages: 668
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
